version: '3'
services:
   db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: KION
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Root123
    container_name: db
   api:
    build: ./back
    ports:
      - 5000:5000
    volumes:
      - static:/app/static
    environment:
      PORT: 5000
      DATABASE_URL: 'postgresql://root:Root123@db:5432/KION'
      SECRET: secret
      FFMPEG: ffmpeg
    depends_on:
      - db
    restart:
      on-failure
    container_name: api
   client:
    build: ./front
    environment:
      VITE_API_URL: http://api:5000/api
    ports:
      - 81:80
    depends_on:
      - api
    restart:
      on-failure
    container_name: client
volumes:
  db-data:
  static:
